modLoader = "javafml"
loaderVersion = "{{ neo_loader_version_range_supported }}"
license = "MIT"
issueTrackerURL = "https://github.com/breakinblocks/Plonk/issues"

[[mods]]
modId = "plonk"
version = "{{ mod_version }}"
displayName = "Plonk"
displayURL = "https://github.com/breakinblocks/Plonk"
logoFile = "pack.png"
credits = "Mojang for Minecraft. Forge for the modding framework. Draconic Evolution for the idea."
authors = "Plonk contributors"
description = "Place items in the world like item frames but on any surface"

[[dependencies.plonk]]
modId = "neoforge"
type="required"
versionRange = "{{ neo_version_range_supported }}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.plonk]]
modId = "minecraft"
type="required"
versionRange = "{{ minecraft_version_range_supported }}"
ordering = "AFTER"
side = "BOTH"
